/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2022 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */
/*Includes ------------------------------------------------------------------*/
#include <stdint.h>
#include "stm32f1xx.h"

#include "RCC.h"
#include "delay.h"

/*Typedef -------------------------------------------------------------------*/

/*Macros --------------------------------------------------------------------*/

/*Global variables ----------------------------------------------------------*/

/*Function prototype --------------------------------------------------------*/

/*Main Function -------------------------------------------------------------*/

int main(void)
{
	HSE_Sysclk();
	/*ejecutar una vez finalizado la configuracion del sysclk*/
	delay_init();

	RCC->APB2ENR |= RCC_APB2ENR_IOPCEN;
	//PC13
	GPIOC->CRH &=~ (GPIO_CRH_CNF13 | GPIO_CRH_MODE13);	//Reset
	GPIOC->CRH |= GPIO_CRH_MODE13_0;
    /* Loop forever */
	for(;;){
		GPIOC->ODR ^= 1U<<13;
		delay_ms(50);
	}
}

/*Function definition -------------------------------------------------------*/

