/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2022 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */
/*Includes ------------------------------------------------------------------*/
#include <stdint.h>
#include "stm32f1xx.h"
#include "defines.h"
#include "RCC.h"
#include <string.h>
#include <stdio.h>
#include "USART.h"
#include "delay.h"
/*Typedef -------------------------------------------------------------------*/

/*Macros --------------------------------------------------------------------*/
#define DEBUG_SERIAL

#ifdef DEBUG_SERIAL
#define SERIAL_PRINTF(...) {printf(__VA_ARGS__);}
#else
#define  SERIAL_PRINTF(...) {}
#endif

#define SW1		A, 2
#define LED		C, 13

/*Global variables ----------------------------------------------------------*/
uint8_t txBuffer[100];
uint8_t rxBuffer[100];
uint16_t len;
/*Function prototype --------------------------------------------------------*/

void USART1_PINConfig(void);

void USART1_Init(void);
/*Main Function -------------------------------------------------------------*/

int main(void)
{
	delay_init();
	//SW1
	RCC->APB2ENR |= GPIOX_CLOCK(SW1);
	GPIOX_MODE(MODE_FF_DIGITAL_INPUT, SW1);
	//GPIOX_ODR(SW1) = 1;						//activa la resistencia pull up
	//LED
	RCC->APB2ENR |= GPIOX_CLOCK(LED);
	GPIOX_MODE(MODE_PP_OUT_50MHZ, LED);
	/*Pinout init*/
	USART1_PINConfig();
	/*usart init*/
	USART_Init(USART1, 8E+6, 115200, USART_CR1_RXNEIE);
	NVIC_EnableIRQ(USART1_IRQn);
    /* Loop forever */

	for(;;){
//		USART_ReceiveData(USART1, rxBuffer, 10);
//		SERIAL_PRINTF("datos recibidos->%s\r\n",rxBuffer);
		if(GPIOX_IDR(SW1) == 1){
			//SE PRESIONA
			SERIAL_PRINTF("1\r\n");
		}else{
			SERIAL_PRINTF("0\r\n");
		}
		delay_ms(50);

	}
}

/*Function definition -------------------------------------------------------*/
void USART1_PINConfig(void){
	//PA9 y PA10
	RCC->APB2ENR |= GPIOX_CLOCK(USART1_TX) | GPIOX_CLOCK(USART1_RX);
	//PA9->TX
	GPIOX_MODE(MODE_PP_ALTER_50MHZ, USART1_TX);
	//PA10->RX
	GPIOX_MODE(MODE_FF_DIGITAL_INPUT, USART1_RX);

	return;
}

void USART1_IRQHandler(void){
	uint8_t temp;
	if(USART1->SR & USART_SR_RXNE){
		temp = USART1->DR;
		if(temp == '1'){
			GPIOX_ODR(LED) = 0;
		}else {
			GPIOX_ODR(LED) = 1;
		}
	}
}
/*****************************************************************/

int __io_putchar(int ch){
	uint8_t c = ch & 0xFFU;
	USART_SendData(USART1, &c, 1);
	return ch;
}
/*****************************************************************/
