/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2022 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */
/*Includes ------------------------------------------------------------------*/
#include <stdint.h>
#include "stm32f1xx.h"
#include "defines.h"
#include "RCC.h"
#include <string.h>
#include <stdio.h>
#include "USART.h"
/*Typedef -------------------------------------------------------------------*/

/*Macros --------------------------------------------------------------------*/
#define DEBUG_SERIAL

#ifdef DEBUG_SERIAL
#define SERIAL_PRINTF(...) {printf(__VA_ARGS__);}
#else
#define  SERIAL_PRINTF(...) {}
#endif



/*Global variables ----------------------------------------------------------*/
uint8_t txBuffer[100];
uint8_t rxBuffer[100];
uint16_t len;
/*Function prototype --------------------------------------------------------*/

void USART1_PINConfig(void);

void USART1_Init(void);
/*Main Function -------------------------------------------------------------*/

int main(void)
{

	/*Pinout init*/
	USART1_PINConfig();
	/*usart init*/
	USART_Init(USART1, 8E+6, 115200, 0);
    /* Loop forever */

	for(;;){

	}
}

/*Function definition -------------------------------------------------------*/
void USART1_PINConfig(void){
	//PA9 y PA10
	RCC->APB2ENR |= GPIOX_CLOCK(USART1_TX) | GPIOX_CLOCK(USART1_RX);
	//PA9->TX
	GPIOX_MODE(MODE_PP_ALTER_50MHZ, USART1_TX);
	//PA10->RX
	GPIOX_MODE(MODE_FF_DIGITAL_INPUT, USART1_RX);

	return;
}


/*****************************************************************/

int __io_putchar(int ch){
	uint8_t c = ch & 0xFFU;
	USART_SendData(USART1, &c, 1);
	return ch;
}
/*****************************************************************/
