/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2022 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include "stm32f4xx.h"
#include "RCC.h"
#include "delay.h"
#include "Config.h"


int main(void)
{
/**********************************************/
	flash_cofig();
	PLL_Config();
/**********************************************/
	delay_initIT(7);
/**********************************************/
	RCC->AHB1ENR |= GPIOX_CLOCK(LED);
	GPIOX_MODER(MODE_OUT,LED);
	GPIOX_OSPEEDR(MODE_SPD_VHIGH,LED);
	GPIOX_PUPDR(MODE_PU_NONE,LED);


	for(;;){
		GPIOX_ODR(LED) ^= 1;
		delay_ms(50);
	}
}
