/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2022 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */
/*Includes ------------------------------------------------------------------*/
/*Includes ------------------------------------------------------------------*/
#include <stdint.h>
#include "stm32f1xx.h"
#include "GPIO_Exti.h"
#include "RCC.h"
#include "delay.h"
#include "defines.h"
#include "LCD.h"
/*Typedef -------------------------------------------------------------------*/

/*Macros --------------------------------------------------------------------*/
#define SW1			B, 11
/*Global variables ----------------------------------------------------------*/
uint32_t count;
/*Function prototype --------------------------------------------------------*/

/*Main Function -------------------------------------------------------------*/

int main(void)
{
	HSE_Sysclk();
	delay_init();
	/*Habitar el reloj para el puerto donde está conectado el Led*/
	RCC->APB2ENR |= GPIOX_CLOCK(LED);
	/*configura en modo salida push pull*/
	GPIOX_MODE(MODE_PP_OUT_50MHZ, LED);
	//LCD INIT
	LCD_Init(16, 2);
    /* Loop forever */
	//PB11 -> ENTRADA DIGITAL CON PULL UP
	RCC->APB2ENR |= GPIOX_CLOCK(SW1);
	GPIOX_MODE(MODE_PU_DIGITAL_INPUT, SW1);
	GPIOX_ODR(SW1) = 1;
	/*Configuracion de la EXTI*/
	EXTI->IMR |= EXTI_IMR_MR11;				//deshabilia el enmascaramiento
	EXTI->FTSR |= EXTI_FTSR_FT11;			// se va detectar flanco descendente
	EXTI->PR |= EXTI_PR_PR11;				//clear
	RCC->APB2ENR |= RCC_APB2ENR_AFIOEN;
	AFIO->EXTICR[2] &=~ (AFIO_EXTICR3_EXTI11);
	AFIO->EXTICR[2] |= AFIO_EXTICR3_EXTI11_PB; //se selecciona el PB11 para generar IT
	/*Configurar los registros de la NVIC*/
	NVIC_SetPriority(EXTI15_10_IRQn, 1);
	NVIC_EnableIRQ(EXTI15_10_IRQn);

	for(;;){




	}
}

/*Function definition -------------------------------------------------------*/
void GPIO_EXTI_Callback(uint8_t pinNumber){
	if(pinNumber == 11){
		count++;
		LCD_Clear();
		LCD_Printf(0, 0, "IT EXTERNA");
		LCD_Printf(0, 1, "COUNT->%d",count);
		GPIOX_ODR(LED) ^= 1U;
	}

}
