/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2022 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */
/*Includes ------------------------------------------------------------------*/
#include <stdint.h>
#include "stm32f1xx.h"
#include "defines.h"
#include "RCC.h"
#include <string.h>
#include <stdio.h>
#include "USART.h"
/*Typedef -------------------------------------------------------------------*/

/*Macros --------------------------------------------------------------------*/
#define DEBUG_SERIAL

#ifdef DEBUG_SERIAL
#define SERIAL_PRINTF(...) {printf(__VA_ARGS__);}
#else
#define  SERIAL_PRINTF(...) {}
#endif



/*Global variables ----------------------------------------------------------*/
uint8_t txBuffer[100];
uint16_t len;
/*Function prototype --------------------------------------------------------*/

void USART1_PINConfig(void);

void USART1_Init(void);
/*Main Function -------------------------------------------------------------*/

int main(void)
{

	/*Pinout init*/
	USART1_PINConfig();
	/*usart init*/
//	USART1_Init();
//
//	len = sprintf((char*)txBuffer, "HOLA MUNDO DESDE USART1\r\n");
//	USART_SendData(USART1, txBuffer, len);
	USART_Init(USART1, 8E+6, 115200, 0);
    /* Loop forever */
	printf("HOLA MUNDO DESDE USART1\r\n");
	SERIAL_PRINTF("ESTE ES UN NUMERO->%d\r\n",10);
	SERIAL_PRINTF("ESTE ES UN NUMERO PI->%.2f\r\n",3.1213424323);
	for(;;){

	}
}

/*Function definition -------------------------------------------------------*/
void USART1_PINConfig(void){
	//PA9 y PA10
	RCC->APB2ENR |= GPIOX_CLOCK(USART1_TX) | GPIOX_CLOCK(USART1_RX);
	//PA9->TX
	GPIOX_MODE(MODE_PP_ALTER_50MHZ, USART1_TX);
	//PA10->RX
	GPIOX_MODE(MODE_FF_DIGITAL_INPUT, USART1_RX);

	return;
}

void USART1_Init(void){
	//habilitar el reloj
	RCC->APB2ENR |= RCC_APB2ENR_USART1EN;
	//configurar los parametros de comunicion
	USART1->CR1 = 0;
	//Paridad
	USART1->CR1 |= USART_CR1_PCE;	//HABILITA LA PARIDAD

	//bits de parada
	//USART1->CR2 |= USART_CR2_STOP_1;	//2 bits de parada
	//velocidad baudios
	/*
	 * Tx/ Rx baud = fCK / (16*USARTDIV)
	 * USARTDIV = [DIV_Mantisa, DIV_Fraction]
	 * USARTDIV = 8MHZ / (16 * 115200)
	 * USARTDIV = 4.3402
	 * DIV_Mantisa = 4
	 * DIV_Fraction = 0.3402 * 16 = 5.444 (Se redondea al entero mas cercano)
	 */
	USART1->BRR = (4U<<4) | 5U;
	//tamño de datos

	//habilitar la T y R

	USART1->CR1 |= USART_CR1_TE;
	USART1->CR1 |= USART_CR1_RE;
	//habilitar el USART1
	USART1->CR1 |= USART_CR1_UE;			//habilitar el USART1
	return;
}

/*****************************************************************/

int __io_putchar(int ch){
	uint8_t c = ch & 0xFFU;
	USART_SendData(USART1, &c, 1);
	return ch;
}
/*****************************************************************/
