/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2022 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */
/*Includes ------------------------------------------------------------------*/
#include <stdint.h>
#include "stm32f1xx.h"
#include "defines.h"
#include "RCC.h"
#include "delay.h"
/*Typedef -------------------------------------------------------------------*/

/*Macros --------------------------------------------------------------------*/
#define LED 		C, 13


/*Global variables ----------------------------------------------------------*/

/*Function prototype --------------------------------------------------------*/
/**
 * @brief configura el TIMER 2 para generar pwm por su canal 2
 * @param [psc]: valor del psc
 * @param [arr]: valor de arr
 */
void TIM2_PWM_Init(uint32_t psc, uint32_t arr);
/*Main Function -------------------------------------------------------------*/

int main(void)
{
	//DELAY INIT
	delay_init();
	/* led init*/
	RCC->APB2ENR |= GPIOX_CLOCK(LED);
	GPIOX_MODE(MODE_PP_OUT_50MHZ, LED);
	//TIMER INIT
	/**
	 * FreqPWM = Fclk/((PSC+1)(ARR+1))
	 * FreqPWM = 8MHZ/(8*1000) = 1000HZ
	 */
	TIM2_PWM_Init(8, 1000);
	TIM2->CCR2 = 500;
    /* Loop forever */
	for(;;){

	}
}

/*Function definition -------------------------------------------------------*/
void TIM2_PWM_Init(uint32_t psc, uint32_t arr){
	/*TIM2/3/4/5_CHx 	->Input capture channel x Input floating
						->Output compare channel x Alternate function push-pull*/
	//enable clock
	RCC->APB2ENR |= GPIOX_CLOCK(TIM2_CH2);
	GPIOX_MODE(MODE_PP_ALTER_50MHZ, TIM2_CH2);
	RCC->APB1ENR |= RCC_APB1ENR_TIM2EN;
	//configuramos el timer
	TIM2->CR1 = 0;
	TIM2->ARR = arr - 1U;
	TIM2->PSC = psc - 1U;
	//configuracion del canal
	TIM2->CCMR1 &=~ (TIM_CCMR1_CC2S);		//MODO DE COMPARACION DE SALIDA
	TIM2->CCMR1 &=~(TIM_CCMR1_OC2M);
	TIM2->CCMR1 |= 6U<<12;					//PWM MODO 1
	TIM2->CCER |= TIM_CCER_CC2E;			//Se habilita el canal como salida

	//Se habilta el conteo
	TIM2->CR1 |= TIM_CR1_CEN;
	TIM2->CCR2 = 0;



	return;
}
