/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2022 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include "stm32f4xx.h"
#include "Config.h"
#include "delay.h"
#include "RCC.h"
/*
#define SRAM_BASE   0x20000000 //MODIFICAR EL BIT 2

#define BIT_2 		*((volatile uint32_t*)(0x22006008UL))
int main(void)
{
	volatile uint32_t *ptr = (volatile uint32_t*) SRAM_BASE;

	*ptr |= 1U<<2;
	*((volatile uint32_t*)(0x20000300)) = 0x0;
	BIT_2 = 1;
	for(;;);
}*/
//#define GPIOX_EN_CLOCK(x)	RCC->AHB1ENR |= RCC_AHB1ENR_GPIO ## x ## EN

int main(void){

	flash_cofig();
	//PLL_Config();			//84MHZ
/************************************************************/
	//RCC_AHB1ENR_GPIOAEN
	RCC->AHB1ENR |= GPIOX_CLOCK(LED);
	GPIO_CLOCK_ENABLE(C);
	//PA -> SALIDA
	GPIOX_MODER(MODE_OUT,LED);
	GPIOX_OSPEEDR(MODE_SPD_VHIGH,LED);
	GPIOX_PUPDR(MODE_PU_NONE,LED);
	//PC13 -> ENTRADA
	GPIOX_MODER(MODE_DIGITAL_INPUT,BUTTON);
	GPIOX_PUPDR(MODE_PU_NONE,BUTTON);
/*************************************************************/
	delay_Init();

	while(1){
		GPIOX_ODR(LED) ^= 1;
		delay_ms(50);
	}
}
